project:
  type: book

book:
  title: "Audio Effects"
  author: "Tobias Hienzsch"
  chapters:
    - index.qmd
    - src/intro.qmd
    - src/overview.qmd
    - src/testing.qmd
    - src/open_source.qmd
    - src/references.qmd

toc: true
number-sections: true
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
  pdf:
    documentclass: scrreprt
    colorlinks: true
    papersize: a4
