project:
  type: book

book:
  title: "Audio Effects"
  author: "Tobias Hienzsch"
  chapters:
    - index.qmd
    - src/introduction.qmd
    - src/math.qmd
    - src/filter.qmd
    - src/dynamic.qmd
    - src/distortion.qmd
    - src/noise.qmd
    - src/frequency.qmd
    - src/delay.qmd
    - src/reverb.qmd
    - src/virtual_analog.qmd
    - src/resample.qmd
    - src/analysis.qmd
    - src/testing.qmd
    - src/open_source.qmd
    - src/references.qmd

toc: true
number-sections: true
bibliography: references.bib

format:
  html:
    theme: darkly
    code-fold: false
    code-tools: true
    mermaid:
      theme: neutral
  pdf:
    documentclass: scrreprt
    colorlinks: true
    papersize: a4
    lot: true
    lof: true
    mermaid:
      theme: neutral
